# Generated by Django 4.1 on 2022-08-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='ticker',
            new_name='cod_acao',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='price_alert',
            new_name='price_watch',
        ),
    ]
